logger:
  name: logger
  namespace: default
  image: quay.io/openshift-logging/cluster-logging-load-client:latest
  tenantId: observatorium

querier:
  name: querier
  namespace: default
  image: quay.io/openshift-logging/cluster-logging-load-client:latest
  tenantId: observatorium

metrics:
  url: http://127.0.0.1:9090
  enableCadvisorMetrics: false
  # Align these with ./prometheus/config.yaml
  jobs:
    distributor: loki-distributor
    ingester: loki-ingester
    querier: loki-querier
    queryFrontend: loki-query-frontend

loki:
  distributor: http://observatorium-xyz-loki-distributor-http.observatorium.svc.cluster.local:3100
  queryFrontend: http://observatorium-xyz-loki-query-frontend-http.observatorium.svc.cluster.local:3100

scenarios:
  highVolumeWrites:
    enabled: true
    configurations:
      - description: "Write 100 logs-per-second"
        samples:
          interval: "60s"
          range: "30s"
          total: 2
        writers:
          replicas: 1
          command: generate
          args:
            destination: loki
            log-lines-rate: 100
  highVolumeReads:
    enabled: true
    configurations:
      - description: "Read 10 queries-per-second"
        samples:
          interval: "15s"
          range: "1m"
          total: 10
        writers:
          replicas: 3
          command: generate
          args:
            destination: loki
            log-lines-rate: 100
        readers:
          startThreshold: 1024000
          replicas: 1
          command: query
          queries:
            sumRateByLevel: 'sum(rate({component!=""}[5m])) by (level)'
          args:
            destination: loki
            log-lines-rate: 10

